spring.kafka.bootstrap-servers=localhost:19092,localhost:19093,localhost:19094
spring.kafka.consumer.auto-offset-reset=earliest

server.port=8081

logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=INFO