spring.kafka.bootstrap-servers=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
spring.kafka.consumer.auto-offset-reset=earliest

server.port=8081

logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=INFO